import xmlrpc.client
import os
from datetime import datetime

ODOO_URL = "http://localhost:8069"
ODOO_DB = "odoo"
ODOO_USER = "digitaldreamers18@gmail.com"
ODOO_PASS = "admin123"

BRIEFING_DIR = "D:/AI-Employee-FTEs/KE_AI_Vault/Briefings"
os.makedirs(BRIEFING_DIR, exist_ok=True)

def generate_ceo_briefing():
    print("📊 Auditing Odoo for Weekly CEO Briefing...")
    try:
        common = xmlrpc.client.ServerProxy(f'{ODOO_URL}/xmlrpc/2/common')
        uid = common.authenticate(ODOO_DB, ODOO_USER, ODOO_PASS, {})
        models = xmlrpc.client.ServerProxy(f'{ODOO_URL}/xmlrpc/2/object')
        
        # 1. Fetch Leads
        leads = models.execute_kw(ODOO_DB, uid, ODOO_PASS, 'crm.lead', 'search_read', [[]], {'fields': ['name', 'contact_name', 'type']})
        
        # 2. Fetch Invoices (Total Revenue)
        invoices = models.execute_kw(ODOO_DB, uid, ODOO_PASS, 'account.move', 'search_read', [[('move_type', '=', 'out_invoice'), ('state', '=', 'posted')]], {'fields': ['amount_total', 'payment_state']})
        
        total_revenue = sum(inv['amount_total'] for inv in invoices)
        pending_payments = sum(inv['amount_total'] for inv in invoices if inv['payment_state'] != 'paid')

        # 3. Create Briefing Content
        briefing_date = datetime.now().strftime("%Y-%m-%d")
        content = f"""---
type: CEO-Briefing
date: {briefing_date}
status: Completed
---

# 🚀 Monday Morning CEO Briefing: K-Electric AI
**Period:** May 1 - May 5, 2026

## 💰 Financial Overview
- **Total Revenue (Invoiced):** {total_revenue:,.2f} PKR
- **Payments Pending:** {pending_payments:,.2f} PKR
- **Collection Rate:** {((total_revenue - pending_payments) / total_revenue * 100) if total_revenue > 0 else 0:.1f}%

## 📈 Sales & CRM Highlights
- **New Leads Captured:** {len([l for l in leads if l['type'] == 'lead' or l['type'] == 'opportunity'])}
- **Top Inquiry:** {leads[0]['name'] if leads else "No active leads"}
- **Status:** Sales pipeline is growing. Focus on Solar installation conversions.

## 🤖 AI Proactive Suggestions
1. **Follow up with Kamran Akmal:** The solar inquiry from North Nazimabad is high-value. Suggest a site survey by tomorrow.
2. **Cost Optimization:** I noticed we are using Salesforce and Odoo simultaneously. Suggest migrating all leads to Local Odoo to save 50,000 PKR/month.
3. **Revenue Growth:** Ali Khan's service was successful. We should offer him a "Summer Maintenance Package" for a recurring fee.

---
*Generated by KE AI Employee v1.0 (Gold Tier)*
"""
        
        file_path = os.path.join(BRIEFING_DIR, f"Weekly_Briefing_{briefing_date}.md")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
            
        print(f"✅ CEO Briefing generated at: {file_path}")
        return file_path

    except Exception as e:
        print(f"❌ Error during Audit: {str(e)}")
        return None

if __name__ == "__main__":
    generate_ceo_briefing()
