import os
import sys
# Add project root to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from skills.odoo_skill import OdooSkill
from datetime import datetime

VAULT_PATH = "D:/AI-Employee-FTEs/KE_AI_Vault"
STATS_FILE = os.path.join(VAULT_PATH, "Dashboard_Stats.md")

def sync_dashboard():
    print("🔄 Syncing Odoo Revenue to Obsidian Dashboard...")
    odoo = OdooSkill()
    summary = odoo.get_revenue_summary()
    
    if isinstance(summary, dict):
        content = f"""---
updated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
---

# 📊 Live Business Stats (Odoo Sync)

| Metric | Value |
| --- | --- |
| **Total Revenue** | {summary['total_revenue']:,.2f} PKR |
| **Pending Payments** | {summary['pending_payments']:,.2f} PKR |
| **Total Invoices** | {summary['count']} |
| **Last Sync** | {datetime.now().strftime("%I:%M %p")} |

---
*Generated by K-Electric AI Engine*
"""
        with open(STATS_FILE, "w", encoding="utf-8") as f:
            f.write(content)
        print("✅ Dashboard Stats updated in Vault.")
    else:
        print(f"❌ Sync failed: {summary}")

if __name__ == "__main__":
    sync_dashboard()
